#!/bin/bash
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -Dartifact=org.biojava:biojava-structure:5.1.1
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install beakerx-jupyterlab
